### ISSUE TITLE
Implement heapster_define_perm

### ISSUE THREAD

**Issue by eddywestbrook** [GaloisInc/heapster-saw#11]
The syntax for this command should be as follows:

heapster_define_recursive_perm *env* *name* *arg_ctx* *value_type* *p*

This defines a new permission name *name* such that *name*<*x1*,...,*xn*> is equivalent to *p*. The arguments are as follows:

* *env* is the Heapster environment object in which *name* is being defined;
* *name* is the new permission name we are defining;
* *arg_ctx* is the context of arguments to name (just like in heapster_define_opaque_perm), i.e., if arg_ctx = x1:tp1, ..., xn:tpn then name<x1, ..., xn> is a permission;
* *value_type* is the type of values to which name applies (also just like in heapster_define_opaque_perm), so that name<x1, ..., xn> is a permission on value_type;
* *p* is the permission that *name*<*x1*,...,*xn*> is defined as.

This command will require adding a notion of defined permissions to the `PermEnv` type in `Permissions.hs`, and will require changing the parsing code in `PermParser.hs` to look up defined names and replace them with their definitions.

An extended feature would be to try to use defined permissions in the printer as well, though that would be more difficult... and should maybe be added as a future feature request.

**Comment by m-yac** [comment]
This has been added in https://github.com/GaloisInc/saw-script/commit/78ee8e281a50291b579a5774d14f8281afaa1914.

> ...and will require changing the parsing code in PermParser.hs to look up defined names and replace them with their definitions.

Note that instead of doing this, I added a `NamedPerm_Defined` constructor to `NamedPerm`, and thus added some rules in `Implication.hs` about folding/unfolding the definitions of defined permissions. @eddywestbrook you may want to do a sanity and/or style check of my changes since this is the first time I'm modifying `Implication.hs`,  but `heapster_define_perm` and everything else seems to be working as expected as far as I can tell.

> An extended feature would be to try to use defined permissions in the printer as well, though that would be more difficult... and should maybe be added as a future feature request.

This should already be working, since defined permissions are not unfolded when parsed.

**Comment by m-yac** [comment]
@eddywestbrook do you think this is done? The only other thing we discussed is whether `heapster_define_perm` should create a new definition in Coq for the named permission or not – it currently does not. My thinking was that this would mean less unfolding when doing Coq proofs, but I could also see why one might want a definition. Let me know if this is a change you want me to make!

**Comment by eddywestbrook** [comment]
I think you are right, that we do not need to make a new Coq definition. I did have an idea for an enhancement, but I can make a separate feature for that.
