### ISSUE TITLE
Allow terms in heapster_define_opaque_perm

### ISSUE THREAD

**Issue by m-yac** [GaloisInc/heapster-saw#3]

**Comment by m-yac** [comment]
This is mostly done - see the HEAD of `wip-heapster`. What I didn't do is actually check the type of the term against the perm type given. I wrote this function:
```
-- | Translate a 'TypRepr' to the SAW core type it represents
translateTypePerm :: SharedContext -> PermEnv -> TypeRepr tp -> IO Term
translateTypePerm sc env typ_perm =
  completeOpenTerm sc $
  transTerm1 $
  runTransM (translate $ emptyMb typ_perm) (emptyTypeTransInfo env)
```
but when run on `"llvmptr 64"` ([this line](https://github.com/GaloisInc/heapster-saw/blob/03fa5241bccc679b3fe37ff0bb0bef361af114bc/examples/string_set.saw#L11) in the test) it gives `(-empty-)` instead of `sort 0`, so if I actually give `translateTypePerm sc env tp` as the type, I get an error. @eddywestbrook is this even the right thing to be doing? If it is, what's going wrong?

**Comment by eddywestbrook** [comment]
You want `typeTransType1`.

**Comment by m-yac** [comment]
Thanks - did you mean replace `transTerm1` with `typeTransType1`? Because unfortunately doing that doesn't fix the problem for me.  (In fact, I think `transTerm1` and `typeTransType1` are identical in the case of a `TypeTrans`.)

**Comment by eddywestbrook** [comment]
Oh, right, of course. Yes, the translation of an `llvmptr` type is empty, because pointers themselves are not translated to anything in SAW. Only their permissions are translated to types that have actual content.

Each permission has type `perm a` for some type `a` that the permission is about. Most of the permissions that are actually used are permissions to values of type `llvmptr 64`, that is, they are permissions to use LLVM pointer values in some way. E.g., an LLVM read permission is a permission to read from a pointer `p`, where `p` has type `llvmptr 64`. So the type you actually want to translate here is `perm (llvmptr 64)`.

Named permissions also have arguments, though, that figure into their types. E.g., the permission `string_set<W,l>` is the application of the permission name `string_set` to the arguments `W` and `l`, where the former is an expression of type `RWModality` and the latter is one of type `Lifetime`. The context argument to `heapster_define_opaque_perm` gives the types of these arguments, which you can translate to a pi-type / function type using `piExprCtx`.

Does this all make sense? Feel free to DM me if you need to.

**Comment by m-yac** [comment]
The [latest commit](https://github.com/GaloisInc/saw-script/commit/0d257da31c20ac9abb042a64f9dcb583213d5ce6) on `wip-heapster` should have this working. Sorry that it took so much explanation for me to just add `ValuePermRepr`, but I feel like I have a much better grasp on the structure of permissions now.

**Comment by eddywestbrook** [comment]
No, it's my bad for not explaining it well! This looks great.
