### ISSUE TITLE
Define heapster_define_recursive_perm

### ISSUE THREAD

**Issue by m-yac** [GaloisInc/heapster-saw#4]

**Comment by eddywestbrook** [comment]
The syntax for this command should be as follows:

heapster_define_recursive_perm *env* *name* *arg_ctx* *value_type* [ *p1*, ..., *pn* ] *trans_tp* *fold_fun* *unfold_fun*

This command defines *name* as a recursive permission that is equivalent to the permission *p1* \\/ ... \\/ *pn*, where the *pi* can contain *name*. The arguments are as follows:

* *env* is the Heapster environment object in which *name* is being defined;
* *name* is the new permission name we are defining;
* *arg_ctx* is the context of arguments to *name* (just like in heapster_define_opaque_perm), i.e., if *arg_ctx* = *x1*:*tp1*, ..., *xn*:*tpn* then *name*<*x1*, ..., *xn*> is a permission;
* *value_type* is the type of values to which *name* applies (also just like in heapster_define_opaque_perm), so that *name*<*x1*, ..., *xn*> is a permission on *value_type*;
* The *pi* are the disjunctive permissions that *name*<*arg_ctx*> unfolds to. These must all be permissions over values of type *value_type* and they can have the variables in *arg_ctx* free.

Note that all of these arguments (except for *env*) are exactly what is needed to build a [`RecPerm`](https://github.com/GaloisInc/heapster-saw/blob/master/src/Verifier/SAW/Heapster/Permissions.hs#L1130) object (including its `NamedPermName`).

**Comment by m-yac** [comment]
I've pushed some progress on this to [`heapster-saw`](https://github.com/GaloisInc/heapster-saw/commit/d2a30d6fd06e3c76246cb5412df75914733ec39a) and [`saw-script`](https://github.com/GaloisInc/saw-script/commit/915d1e76e0ead704ef08af7fb86c5724fbbc691f). Currently *fold_fun* and *unfold_fun* are required to be `Ident`s and are not typechecked, I plan to remedy that tomorrow.

There are two changes worth noting. One is that I added a [perm expressions](https://github.com/GaloisInc/heapster-saw/commit/d2a30d6fd06e3c76246cb5412df75914733ec39a#diff-18805fe0b6a80e5fc2a2075debad5282R94) field to `ParserEnv` so that *p1,...,pn* can refer to *name* while being parsed - not sure if this is the best way to do this. The other is [this change](https://github.com/GaloisInc/heapster-saw/commit/d2a30d6fd06e3c76246cb5412df75914733ec39a#diff-7453c5f9651c9004bcaa2cb735b65cd0R1320), which is necessary if we want to allow arbitrary terms for *trans_tp* (at least the way I'm doing it).

I also added a `rec_perm_test.saw` example that should probably be removed once this feature is working.

**Comment by m-yac** [comment]
Ok, I believe this issue is done – I've pushed changes to [`heapster-saw`](https://github.com/GaloisInc/heapster-saw/commit/c98f3268646203e3828ec659c2fe7c9b579b59e1) and [`saw-script`](https://github.com/GaloisInc/saw-script/commit/6bacfdb328ef5a26eb5702df6c35baa6396dc569).

Note that I removed both `RecPerm` definitions from the default heapster environment and added the appropriate definitions to [`linked_list.saw`](https://github.com/GaloisInc/heapster-saw/blob/deba40b451e7df68ae5fc100263e96acd0fee4d8/examples/linked_list.saw#L5) and [`poly_linked_list.saw`](https://github.com/GaloisInc/heapster-saw/blob/deba40b451e7df68ae5fc100263e96acd0fee4d8/examples/poly_linked_list.saw#L5), thought the latter doesn't typecheck for other reasons.

**Comment by eddywestbrook** [comment]
Nice job!
